---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: apigee-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apigee-config
  namespace: apigee-config
data:
  mgmt_api: http://35.184.57.218:8080/v1
  username: opdk@apigee.com
  password: Secret123
  org_name: demo
  env_name: test
