---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: apigee-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apigee-config-saas
  namespace: apigee-config
data:
  mgmt_api: https://api.enterprise.apigee.com/v1
  username: apigee-xx@apigee.com
  password: xcxcxcxcxc
  token_url: https://login.apigee.com/oauth/token
  #mfa_token: "695573"
  org_name: imedusa
  env_name: test
  profile: legacy
  auth: token
