---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: apigee-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apigee-config
  namespace: apigee-config
data:
  mgmt_api: https://api.enterprise.apigee.com/v1
  username:
  password:
  token_url: 
  org_name: demo
  env_name: test
  type: legacy
  auth: Bearer
