# permissions for end users to view apiproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apiproxy-viewer-role
rules:
- apiGroups:
  - apigee.google.com
  resources:
  - apiproxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apigee.google.com
  resources:
  - apiproxies/status
  verbs:
  - get
