# permissions for end users to view developerapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developerapp-viewer-role
rules:
- apiGroups:
  - apigee.google.com
  resources:
  - developerapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apigee.google.com
  resources:
  - developerapps/status
  verbs:
  - get
