# permissions for end users to edit developerapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developerapp-editor-role
rules:
- apiGroups:
  - apigee.google.com
  resources:
  - developerapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigee.google.com
  resources:
  - developerapps/status
  verbs:
  - get
