apiVersion: apigee.google.com/v1
kind: ApiProduct
metadata:
  name: my-samples
spec:
  # Add fields here
  apiResources:
  -  "/"
  -  "/*"
  name: my-api-product
  approvalType: auto
  description: API Product demo CRD
  displayName: API Product demo CRD
  attributes:
  - name: access
    value: public
  - name: apigee-remote-service-targets
    value: httpbin.default.svc.cluster.local
  environments:
  - test
  proxies:
  - remote-service
 # scopes: 
 # quota : 1
 # quotaInterval : 1
 # quotaTimeUnit : minute
